Add env vars for IP reconcile intervals
aws/amazon-vpc-cni-k8s pull request #1280
Opened 2020-11-05 18:10 UTC by jacksontj

**What type of PR is this?**

feature

**Which issue does this PR fix**:
#817 

**What does this PR do / Why do we need it**:
Adds config options to reduce AWS API callc ount.

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-11-05 18:44 UTC, jayanthvn commented
Hi @jacksontj 

Thanks for opening the PR, we will review it. Can you please kindly attach UT cases and fill the remaining questions in the PR template?

Appreciate your help on this.

2020-11-05 19:27 UTC, jacksontj commented
I think I've answered most of the questions here; I'm not sure what UT cases means though?

2020-11-05 19:33 UTC, couralex6 commented
@jacksontj UT = unit tests :)

2020-11-05 19:35 UTC, jayanthvn commented
> I think I've answered most of the questions here; I'm not sure what UT cases means though?

Thank you for updating the template. Mainly few logs attached from IPAMD showing the new variables are honored during IP reconciliation, scenario when environment variable is not set and interval fall back to default interval, downgrade/upgrade scenario with just image change and having the env variables set. Sorry for the trouble but this will help reviewers and others using this feature.

2021-01-15 21:50 UTC, jayanthvn requested changes

2021-01-15 21:50 UTC, jayanthvn commented on pkg/ipamd/introspect.go
> +		if input < 0 {
I think we should cap the min to be `defaultNodeIPPoolReconcileInterval` for `NodeIPPoolReconcileInterval` and `defaultDecreaseIPPoolInterval` for `DecreaseIPPoolInterval`. Anything below the defaults will be way too aggressive and lot of ec2 calls.

2021-08-02 21:20 UTC, jayanthvn commented
PR needs rebase and also we have to update the README for new variable.  Also we need to set floor for the variable as mentioned here - https://github.com/aws/amazon-vpc-cni-k8s/pull/1280#discussion_r558611232

2022-05-05 23:02 UTC, jayanthvn commented
/not stale

2022-12-11 00:04 UTC, closed without merging