README: mention arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
aws/amazon-vpc-cni-k8s pull request #1768
Opened 2021-11-25 18:26 UTC by aviau

2021-11-29 18:41 UTC, Shreya027 commented
Hi, I reviewed the addition to the README. It would be good to rephrase as follows:


>The above policy is available under: ```arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy``` as a part of AWS managed policies  for EKS ( Ref:  https://docs.aws.amazon.com/eks/latest/userguide/security-iam-awsmanpol.html ).


I will review again once the change is made. Thanks.

2021-11-29 18:46 UTC, Shreya027 requested changes
Hi, I reviewed the addition to the README. It would be good to rephrase as follows:


>The above policy is available under: ```arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy``` as a part of AWS managed policies  for EKS ( Ref:  https://docs.aws.amazon.com/eks/latest/userguide/security-iam-awsmanpol.html ).


I will review again once the change is made. Thanks.

2021-11-29 20:37 UTC, aviau commented
@Shreya027 done!

2021-12-06 17:54 UTC, Shreya027 approved these changes

2021-12-06 17:55 UTC, merged