Add workflow to sync cni-metrics-helper helm chart to eks-charts
aws/amazon-vpc-cni-k8s pull request #1794
Opened 2021-12-15 00:14 UTC by oliviassss

**What type of PR is this?**
Enhancement

**Which issue does this PR fix**:
ORR task

**What does this PR do / Why do we need it**:
Added a workflow to sync cni-metrics-helper helm chart to eks-charts repo.

- Modified the existing script to enable user to choose which chart to sync, currently there are 2 options: 1) aws-vpc-cni and 2) cni-metrics-helper. In the future we can modify the select menu if needed.

**Testing done on this change**:

- Tested sync from aws/amazon-vpc-cni-k8s to oliviassss/eks-charts repo

   - for aws-vpc-cni: [https://github.com/oliviassss/eks-charts/pull/5/](https://github.com/oliviassss/eks-charts/pull/5)
   - for cni-metrics-helper: [https://github.com/oliviassss/eks-charts/pull/6/](https://github.com/oliviassss/eks-charts/pull/6)

**Automation added to e2e**:

N/A
**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
N/A

**Does this change require updates to the CNI daemonset config files to work?**:

No
**Does this PR introduce any user-facing change?**:

No
```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-21 05:28 UTC, jayanthvn requested changes
You will have to update this - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/Makefile#L42 so that this gets https://github.com/aws/amazon-vpc-cni-k8s/blob/master/Makefile#L286 both aws-vpc-cni and metrics helper as arguments.

2022-01-13 22:07 UTC, oliviassss commented
@jayanthvn sorry for the delay, please review the latest change. Have modified both `make ekscharts-sync-release`  and `make ekscharts-sync` in Makefile.

2022-02-28 19:52 UTC, jayanthvn submitted a review, later dismissed
lgtm

2022-05-09 18:10 UTC, jayanthvn submitted a review, later dismissed

2022-10-12 14:53 UTC, jdn5126 commented
Discarding this PR as this workflow is not currently needed. This can be reintroduced in the future if needed

2022-10-12 15:43 UTC, jayanthvn commented
We need to keep the PR open, it is reviewed and pending merge. This is needed to sync cni metrics helper to eks-charts.

2022-12-09 16:24 UTC, jdn5126 requested changes

2022-12-09 16:24 UTC, jdn5126 commented on Makefile
> +		${MAKEFILE_PATH}/scripts/sync-to-eks-charts.sh -b $$HELM_CHART_NAME -r ${REPO_FULL_NAME} ; \
I think the `$$` may cause an issue here

2022-12-09 16:24 UTC, jdn5126 commented on Makefile
> +		${MAKEFILE_PATH}/scripts/sync-to-eks-charts.sh -b $$HELM_CHART_NAME -r ${REPO_FULL_NAME} -n -y ; \
same here, I think we need single `$`

2022-12-14 17:23 UTC, jdn5126 commented on Makefile
> +		${MAKEFILE_PATH}/scripts/sync-to-eks-charts.sh -b $$HELM_CHART_NAME -r ${REPO_FULL_NAME} -n -y ; \
nvm, this is right for Makefiles, my bad

2022-12-14 17:23 UTC, jdn5126 commented on Makefile
> +		${MAKEFILE_PATH}/scripts/sync-to-eks-charts.sh -b $$HELM_CHART_NAME -r ${REPO_FULL_NAME} ; \
nvm, this is right for Makefiles, my mistake

2022-12-14 19:48 UTC, jdn5126 approved these changes

2022-12-14 19:48 UTC, merged