adding ip check for annotatePod in ipamd
aws/amazon-vpc-cni-k8s pull request #2328
Opened 2023-03-23 22:01 UTC by jerryhe1999

**What type of PR is this?**
bug

**Which issue does this PR fix**:
#2281 

**What does this PR do / Why do we need it**:
This PR adds a check login in annotatePod() of ipamd.go to make sure when deleting the Pod IP, the IP is the one we are releasing.

**Testing done on this change**:
New unit test added in ipamd_test.go. Both unit tests and integration tests passed.

**Automation added to e2e**:
N/A

**Will this PR introduce any new dependencies?**:
No

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No

**Does this change require updates to the CNI daemonset config files to work?**:
No

**Does this PR introduce any user-facing change?**:
No

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-27 16:03 UTC, jdn5126 requested changes
Changes are looking good, mostly nits. Before submitting, can you make sure `make check-format` passes? You can run `go fmt` on the files you modified to get the formatting fixed.

2023-03-27 16:03 UTC, jdn5126 commented on pkg/ipamd/ipamd_test.go
> +	assert.Error(t, err)
Let's check that the value of `err` here is as expected

2023-03-27 16:03 UTC, jdn5126 commented on pkg/ipamd/rpc_handler.go
> -		s.ipamContext.AnnotatePod(in.K8S_POD_NAME, in.K8S_POD_NAMESPACE, vpccniPodIPKey, ipv4Addr)
nit: let's add a comment here that on ADD, we pass empty string as there is no IP being released

2023-03-27 16:03 UTC, jdn5126 commented on pkg/ipamd/rpc_handler.go
> +		s.ipamContext.AnnotatePod(in.K8S_POD_NAME, in.K8S_POD_NAMESPACE, vpccniPodIPKey, "", ip)
nit: let's add a comment that on DEL, we pass IP being released

2023-03-27 22:48 UTC, jerryhe1999 commented
@jdn5126 Have updated a new commit, could you have look on it? Thank you!

2023-03-27 22:54 UTC, jdn5126 requested changes
A few last nits, then this looks good to me

2023-03-27 22:54 UTC, jdn5126 commented on pkg/ipamd/ipamd.go
> +		// On CNI ADD, always set new annotation
nit: this comment should go below the next line

2023-03-27 22:54 UTC, jdn5126 commented on pkg/ipamd/ipamd.go
> +			//If the new pod annotation is as the same as the old one, return immediately without extra cost
nit: space after comment, and maybe rephrase it as "Skip patch operation if new value is the same as existing value"

2023-03-27 22:54 UTC, jdn5126 commented on pkg/ipamd/ipamd_test.go
> +	assert.Equal(t, fmt.Errorf("Released IP 10.0.0.1 does not match existing annotation. Not patching pod."), err)
nit: use `ipOne` here to simplify check

2023-03-27 22:54 UTC, jdn5126 commented on pkg/ipamd/ipamd_test.go
> +	//Test basic add operation for new pod
nit: let's add a space after comment. I am surprised this didn't get done by `go fmt`, but maybe you have an older go installation

2023-03-28 15:52 UTC, jdn5126 requested changes

2023-03-29 22:10 UTC, jdn5126 approved these changes

2023-03-29 22:10 UTC, merged