Reduce API calls
aws/amazon-vpc-cni-k8s pull request #2575
Opened 2023-09-18 23:47 UTC by jchen6585

**What type of PR is this?**

**Which issue does this PR fix**:
#2160 

**What does this PR do / Why do we need it**:
Reduces unnecessary API calls when custom networking is not used.

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

Manually tested against IPAMD/Custom-Networking integration test suites. Manually checked cloudwatch to see decrease in API calls.

**Automation added to e2e**:

No

**Will this PR introduce any new dependencies?**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No, no

**Does this change require updates to the CNI daemonset config files to work?**:

No

**Does this PR introduce any user-facing change?**:

No

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-09-18 23:57 UTC, jchen6585 commented
https://github.com/aws/amazon-vpc-cni-k8s/actions/runs/6229286457
CNI suite failing locally, but pretty sure it is a cluster issue and not something wrong with the code. Running this to be sure.

2023-09-19 15:01 UTC, jdn5126 requested changes

2023-09-19 15:01 UTC, jdn5126 commented on pkg/ipamd/ipamd.go
> +	if c.useCustomNetworking {
nit: Let's add a comment here that when Custom Networking is enabled and a valid ENIConfig is found, IPAMD patches the `CNINode` resource for this instance. This operation is safe as enabling/disabling Custom Networking requires terminating the previous instance.

2023-09-19 16:37 UTC, jdn5126 approved these changes

2023-09-19 17:22 UTC, merged