Multi-subnet [DRAFT]
aws/amazon-vpc-cni-k8s pull request #2660
Opened 2023-11-09 21:47 UTC by jchen6585

**What type of PR is this?**

feature
**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

Still need to figure out how to update custom networking suite

**Will this PR introduce any new dependencies?**:

Yes

**Will this break upgrades or downgrades? Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

No

**Does this PR introduce any user-facing change?**:

Yes

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-09 21:52 UTC, jchen6585 commented on pkg/awsutils/awsutils.go
> +		log.Infof("THIS IS THE SUBNET ID: %s", *element.SubnetId)
these are just some debug statements when i was manually testing, will remove

2023-11-10 20:06 UTC, jdn5126 requested changes

2023-11-10 20:06 UTC, jdn5126 commented on charts/aws-vpc-cni/crds/customresourcedefinition.yaml
> +              oneOf:
Nice find!

2023-11-10 20:06 UTC, jdn5126 commented on pkg/awsutils/awsutils.go
> +	describeSubnetInput := &ec2.DescribeSubnetsInput{
This should only be done for custom networking, as in the normal case, we do not want to make a Describe call

2023-11-10 20:06 UTC, jdn5126 commented on pkg/awsutils/awsutils.go
> +	sort.SliceStable(result.Subnets, func(i, j int) bool {
nit: Can you add a comment here that we sort subnets by available IP address count before determining the subnet to use?

2023-11-10 20:06 UTC, jdn5126 commented on pkg/ipamd/ipamd.go
> +		log.Infof("ipamd: using custom network config: %v, %s", eniCfg.SecurityGroups, eniCfg.Subnets)
nit: Let's move this log to below when we find which field to use

2024-01-28 00:03 UTC, closed without merging